### ISSUE TITLE
Cannot compile application with @angular-package/prism

### ISSUE THREAD

**Issue by gcherem** [angular-package/angular-package#28]
I am getting the following errors when I try to compile an application with package @angular-package/prism:

ERROR in ./node_modules/@angular-package/prism/rxjs/prism.component.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\...\node_modules\@angular-package\prism\rxjs'
ERROR in ./node_modules/@angular-package/prism/rxjs/prism.service.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\...\node_modules\@angular-package\prism\rxjs'
ERROR in ./node_modules/@angular-package/prism/rxjs/prism.service.js
Module not found: Error: Can't resolve 'rxjs/Observer' in 'C:\...\node_modules\@angular-package\prism\rxjs'
ERROR in ./node_modules/@angular-package/prism/node_modules/@angular-package/reactive/decorator/subscribe/src/subscribe-on-init.func.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\...\node_modules\@angular-package\prism\node_modules\@angular-package\reactive\decorator\subscribe\src'
ERROR in ./node_modules/@angular-package/prism/rxjs/prism.service.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\...\node_modules\@angular-package\prism\rxjs'
ERROR in ./node_modules/@angular-package/prism/node_modules/@angular-package/reactive/decorator/unsubscribe/src/unsubscribe-on-destroy.func.js
Module not found: Error: Can't resolve 'rxjs/Subscription' in 'C:\...\node_modules\@angular-package\prism\node_modules\@angular-package\reactive\decorator\unsubscribe\src'
ERROR in ./node_modules/@angular-package/prism/rxjs/prism.component.js
Module not found: Error: Can't resolve 'rxjs/Subscription' in 'C:\...\node_modules\@angular-package\prism\rxjs'
ERROR in ./node_modules/@angular-package/prism/rxjs/prism.service.js
Module not found: Error: Can't resolve 'rxjs/Subscription' in 'C:\...\node_modules\@angular-package\prism\rxjs'
ERROR in ./node_modules/@angular-package/prism/rxjs/prism.interface.js
Module not found: Error: Can't resolve 'rxjs/Subscription' in 'C:\...\node_modules\@angular-package\prism\rxjs'

I am using:
Angular 8.2.13
rxjs 6.5.3

Seems that it doesnt support the path /Subject and /Subscription in the import statements.

Am I missing something? Workarounds?

Thanks in advance!

**Comment by sciborrudnicki** [comment]
Let me try to reproduce your issue.

**Comment by angularpackage** [comment]
npm install --save rxjs-compat
